set serveroutput on;
--RECAPITULANDO LO QUE ES UN BLOQUE PL SQL

DECLARE
nombre varchar2(20):='Fernando Daniel';

BEGIN 
DBMS_OUTPUT.PUT_LINE('BUENAS NOCHES '||nombre);
END;
/



DECLARE
edad INTEGER:=20;
dias INTEGER;
estatus VARCHAR2(12);
BEGIN
dias:=edad*365;

if dias >10000 then
estatus:= 'viejo';
else
estatus:='joven';
END IF;
DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES  '||dias||' ESTATUS: ' || estatus);
END;
/


--VEREMOS NUESTRO PRIMER PROCEDIMIENTO ALMACENADO 
CREATE OR REPLACE PROCEDURE SALUDAR(mensaje IN varchar2)
AS
BEGIN
DBMS_OUTPUT.PUT_LINE('HOLA BUENAS NOCHES ' ||mensaje);
END;
/

--ejecutamos el procedimiento

exec saludar (' fernando velazquez');

--generamos la secuencia

CREATE SEQUENCE SEC_PERSONA
START WITH 1 --EMPEZAR EN 
INCREMENT BY 1 -- INCREMENTAR EN 
NOMAXVALUE; --NO TIENE LIMITE SUPERIOR MILLONES DE REGISTROS

--GENERAMOS LA TABLA
CREATE TABLE PERSONA(ID_PERSONA INTEGER,
NOMBRE VARCHAR2(20), EDAD INTEGER,
CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA));


CREATE OR REPLACE PROCEDURE GUARDAR_PERSONA (MY_ID OUT INTEGER,MY_NOMBRE IN VARCHAR2, MY_EDAD IN INTEGER)
AS
BEGIN
SELECT  SEC_PERSONA.NEXTVAL INTO MY_ID FROM DUAL; 
INSERT INTO PERSONA VALUES (MY_ID,MY_NOMBRE,MY_EDAD);
END; 
/

declare
VALOR INTEGER;
BEGIN
GUARDAR_PERSONA(VALOR,'JUAN',23);
END;
/
SELECT * FROM PERSONA; 
