CREATE TABLE USUARIO_INICIAL (ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(40), SUELDO_BASE INTEGER);
CREATE TABLE RESPALDO_USUARIOINICIAL(ID INTEGER , NOMBRE VARCHAR2(40), SUELDO_BASE INTEGER);


--ESTOS VALORES SE INSERTARAN AL ULTIMO YA QUE SE PROBARA SI AL INSERTAR EL CUARTO USUARIO SE 
--BORRAN LOS OTROS TRES.
INSERT INTO USUARIO_INICIAL VALUES(1,'ROGER', 1200);
INSERT INTO USUARIO_INICIAL VALUES(2,'MICH', 1800);
INSERT INTO USUARIO_INICIAL VALUES(3,'KARENKA',2100);

CREATE OR REPLACE PROCEDURE CONTAR(NUMERO OUT INTEGER)
AS
BEGIN
SELECT COUNT(*) INTO NUMERO FROM USUARIO_INICIAL;

DBMS_OUTPUT.PUT_LINE('ENCONTRADOS  '||NUMERO);
END;
/

DECLARE 
VALORES INTEGER;
BEGIN
CONTAR(VALORES);
END;
/

-- EL QUE COPIA
CREATE OR REPLACE PROCEDURE COPIAR 
AS
CURSOR CUR_USUARIO_INICIAL IS SELECT * FROM USUARIO_INICIAL;
BEGIN
FOR REC IN CUR_USUARIO_INICIAL LOOP
INSERT INTO RESPALDO_USUARIOINICIAL VALUES(REC.ID, REC.NOMBRE, REC.SUELDO_BASE);
END LOOP;
END;
/

CREATE OR REPLACE TRIGGER DISP_USUARIO_INICIAL BEFORE INSERT ON USUARIO_INICIAL FOR EACH ROW
DECLARE
VALORES INTEGER;
BEGIN
CONTAR(VALORES);
IF  VALORES = 3 THEN
COPIAR();
DELETE FROM USUARIO_INICIAL;
END IF;
END;
/
------------------------------------------------------
INSERT INTO USUARIO_INICIAL VALUES(4,'JOSE',4200);
INSERT INTO USUARIO_INICIAL VALUES(5,'LUPITA',1950);
INSERT INTO USUARIO_INICIAL VALUES(6,'ROSA',2100);

INSERT INTO USUARIO_INICIAL VALUES(7,'MANUEL',2820);

SELECT * FROM USUARIO_INICIAL;
SELECT * FROM RESPALDO_USUARIOINICIAL;
